sudo: false

language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gitconfig

before_install:
  - cp .travis/settings.xml $HOME/.m2/settings.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
